#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH=/usr/local/bin:~/scripts:$PATH:/usr/sbin:/sbin

# pip should only run if there is a virtualenv currently activated
export PIP_REQUIRE_VIRTUALENV=true
# cache pip-installed packages to avoid re-downloading
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache

syspip(){
   PIP_REQUIRE_VIRTUALENV="" pip "$@"
}

#Google Go (Golang)
export GOPATH=$HOME/projects/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/usr/local/opt/go/libexec/bin

#Haskell/Cabal
export PATH=$HOME/.cabal/bin:$PATH

#Node.JS

if [[ -s $HOME/.nvm ]];
 then 
	setopt nullglob 
	NVM_DIR=$HOME/.nvm 
	source $NVM_DIR/nvm.sh 
fi

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory extendedglob
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '${ZDOTDIR:-$HOME}.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Add homebrew to the completion path
fpath=("/usr/local/bin/" $fpath)

# RVM
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# TextMate
export EDITOR="/usr/local/bin/mate -w"

#For brewed OpenSSH
eval $(ssh-agent)

function cleanup {
  echo "Killing SSH-Agent"
  kill -9 $SSH_AGENT_PID
}

trap cleanup EXIT
