#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

PATH=/usr/local/bin:$PATH

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

export PATH
# pip should only run if there is a virtualenv currently activated
export PIP_REQUIRE_VIRTUALENV=true
# cache pip-installed packages to avoid re-downloading
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache

syspip(){
   PIP_REQUIRE_VIRTUALENV="" pip "$@"
}

#Google Go (Golang)
export GOPATH=$HOME/projects/go
export PATH=$PATH:$GOPATH/bin

#Haskell/Cabal
export PATH=$HOME/.cabal/bin:$PATH

#Node.JS

if [[ -s $HOME/.nvm ]];
 then 
	setopt nullglob 
	NVM_DIR=$HOME/.nvm 
	source $NVM_DIR/nvm.sh 
fi
